In [1]:
import numpy as np
import pandas as pd

# **Task - 1 Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)**

In [13]:
data=np.random.randint(0,100,size=(4,4))
df=pd.DataFrame(data,columns=['F1', 'F2', 'F3', 'F4'],index=['Ob1', 'Ob2', 'Ob3', 'Ob4'])
df

     F1  F2  F3  F4
Ob1  60  62  14  55
Ob2  79  10   9   3
Ob3  97  50  76  86
Ob4  13  50  59  39

# **Task - 2 Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'**

In [17]:
df.rename(columns= {'F1': 'Rv_1','F2': 'Rv_2','F3': 'Rv_3','F4': 'Rv_4'})
df

     Rv_1  Rv_2  Rv_3  Rv_4
Ob1    60    62    14    55
Ob2    79    10     9     3
Ob3    97    50    76    86
Ob4    13    50    59    39

# **Task - 3 Find the descriptive statistics of the 'df' dataframe**

In [18]:
df.describe()

            Rv_1       Rv_2       Rv_3       Rv_4
count   4.000000   4.000000   4.000000   4.000000
mean   62.250000  43.000000  39.500000  45.750000
std    36.142081  22.715633  33.131053  34.538626
min    13.000000  10.000000   9.000000   3.000000
25%    48.250000  40.000000  12.750000  30.000000
50%    69.500000  50.000000  36.500000  47.000000
75%    83.500000  53.000000  63.250000  62.750000
max    97.000000  62.000000  76.000000  86.000000

# **Task - 4 Check for the null values in 'df' and find the data type of the columns.**

In [19]:
df.isnull()

      Rv_1   Rv_2   Rv_3   Rv_4
Ob1  False  False  False  False
Ob2  False  False  False  False
Ob3  False  False  False  False
Ob4  False  False  False  False

In [24]:
df.dtypes

Rv_1    int64
Rv_2    int64
Rv_3    int64
Rv_4    int64
dtype: object

# **Task - 5 Display the 'Random value 2' & 'Random value 3' columns with location method and index location method**

using **loc[]**

In [47]:
df.loc[:,["Rv_2","Rv_3"]]

     Rv_2  Rv_3
Ob1    62    14
Ob2    10     9
Ob3    50    76
Ob4    50    59

using **iloc[]**

In [30]:
df.iloc[:,[1,2]]

     Rv_2  Rv_3
Ob1    62    14
Ob2    10     9
Ob3    50    76
Ob4    50    59

In [2]:
!git init
!git clone https://github.com/Shalavya8103/Coursework.git

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
Cloning into 'Coursework'...
warning: You appear to have cloned an empty repository.